artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/109ab15c6f7d4c0db1aa884a57d1204d/artifacts
end_time: 1728986961781
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 109ab15c6f7d4c0db1aa884a57d1204d
run_name: Default
run_uuid: 109ab15c6f7d4c0db1aa884a57d1204d
source_name: ''
source_type: 4
source_version: ''
start_time: 1728986961770
status: 3
tags: []
user_id: mle-user
