artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/fa0fecf3720c442dbea2d6f40666868c/artifacts
end_time: 1728987367592
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: fa0fecf3720c442dbea2d6f40666868c
run_name: Default
run_uuid: fa0fecf3720c442dbea2d6f40666868c
source_name: ''
source_type: 4
source_version: ''
start_time: 1728987367580
status: 3
tags: []
user_id: mle-user
